name: Pull Request checks

on:
  pull_request:

  push:
    branches: [master]

jobs:
  linting-check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: clean
        run: make clean

      - name: install npm
        run: make install-npm

      - name: Spell check Markdown files
        run: make spellcheck-markdown

      - name: Lint Markdown files
        run: make lint-markdown
